#!/usr/bin/expect -f

set timeout -1

spawn mysql_secure_installation 

send -- "\r"

expect "Set root password?"

send -- "y\r"

expect "New password:"

send -- "admin\r"

expect "Re-enter new password:"

send -- "admin\r"

expect "Remove anonymous users?"

send -- "y\r"

expect "Disallow root login remotely?"

send -- "y\r"

expect "Remove test database and access to it?"

send -- "y\r"

expect "Reload privilege tables now?"

send -- "y\r"

expect eof
